---
# - name: Create tarballs directory
#   file:
#     path: "{{ tarballs_dir }}"
#     state: directory
#   tags:
#     - setup

- name: Application | Setup Phoenix Application
  include_role:
    name: phoenix
  when: phoenix is defined

- name: Get live app version number
  shell: |
    if [ -f '{{ app_dir }}/releases/start_erl.data' ]; then
      cut -d' ' -f2 '{{ app_dir }}/releases/start_erl.data'
    else
      echo ""
    fi
  register: vsn_live
  changed_when: false
  tags:
    - deploy

- set_fact:
    vsn_live: "{{ vsn_live.stdout }}"
  tags:
    - deploy

- name: EX Application | Clone or pull git repository
  when: erlang_version is defined and elixir_version is defined and phoenix_version is defined
  become: yes
  become_user: "{{ project_user }}"
  git: >
    repo={{ repo.url }}
    dest={{ project_src }}
    version={{ repo.version }}
    accept_newhostkey=yes
    force=yes
    update=yes
  tags:
    - deploy

- name: EX Application | Copy dev.exs config
  when: erlang_version is defined and elixir_version is defined and phoenix_version is defined
  become: yes
  become_user: "{{ project_user }}"
  file:
    src: '{{ project_src }}/config/{{ dev_exs_config }}'
    dest: '{{ project_src }}/config/dev.exs'
    state: link
  tags:
    - deploy

- name: EX Application | Get next app version number
  shell:
    cmd: "grep -Po '(?<=version: \")[^\"]+' {{ project_src }}/mix.exs"
  register: vsn_next
  changed_when: false
  tags:
    - deploy

- set_fact:
    vsn_next: "{{ vsn_next.stdout }}"
  tags:
    - deploy

- name: EX Application | Fail if the versions match
  fail:
    msg: "The live version ({{ vsn_live }}) matches the next version ({{ vsn_next }}). Deployment should not proceed."
  when: vsn_next == vsn_live
  tags:
    - deploy

- name: EX Application | sh env
  ansible.builtin.shell:
  args:
    cmd: "{{ shenv_cmd }}"
    chdir: '{{ ansible_user_dir }}/'
  register: shenv
  when: erlang_version is defined and elixir_version is defined and phoenix_version is defined

- name: EX Application | Run mix release
  become_user: "{{ project_user }}"
  shell: |
    {{ source }}
    cd {{ project_src }} && \
    mix deps.get --only prod && \
    MIX_ENV=prod mix do compile, assets.deploy, release
  args:
    executable: '{{ ansible_user_shell }}'
  # args:
  #   creates: "{{ project_src }}/_build/prod/{{ project_name }}-{{ vsn_next }}.tar.gz"
  when: erlang_version is defined and elixir_version is defined and phoenix_version is defined
  vars: 
    source: "{{ shenv.stdout_lines | map('regex_replace', '(^)', '. ') | join('\n') }}"
  tags:
    - deploy

- name: EX Application | Run mix system.d init and generate
  shell: |
    cd {{ project_src }} && \
    SYSTEM_USER={{ project_user }} SYSTEM_GROUP={{ project_group }} MIX_ENV=prod mix systemd.generate
  become_user: "{{ project_user }}"
  tags:
    - deploy

- name: EX Application | Link application to systemd
  when: erlang_version is defined and elixir_version is defined
  become: yes
  file:
    src: '{{ project_src }}/_build/prod/systemd/lib/systemd/system/{{ project_name }}.service'
    dest: '/etc/systemd/system'
    state: link
  tags:
    - deploy

- name: EX Application | Create .env file
  when:
    - dot_env_file.dest is defined 
    - dot_env is defined
    - vsn_next != vsn_live
  become: yes
  become_user: "{{ project_user }}"
  template:
    src: env-file.template
    dest: "{{ dot_env_file.dest }}"
    owner: "{{ dot_env_file.owner | default(omit) }}"
    group: "{{ dot_env_file.group | default(omit) }}"
    mode: "{{ dot_env_file.mode | default(omit) }}"
    backup: "{{ dot_env_file.backup | default(omit) }}"
    force: "{{ dot_env_file.force | default(True) }}"
    validate: "{{ dot_env_file.validate | default(omit) }}"
    selevel: "{{ dot_env_file.selevel | default(omit) }}"
    serole: "{{ dot_env_file.serole | default(omit) }}"
    setype: "{{ dot_env_file.setype | default(omit) }}"
    seuser: "{{ dot_env_file.seuser | default(omit) }}"
  notify: start EX Application
  tags:
    - deploy
