---
- name: redis | Install system packages
  when: redis is defined
  become: yes
  apt: >
    pkg=redis
    state=present
    update-cache=yes
  tags:
    - setup

- name: redis | Enable on boot
  when: redis is defined
  become: yes
  systemd: >
    name=redis
    enabled=yes
    state=started
  tags:
    - setup
