---
- name: Add ppa:eilander repo for compression support
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:eilander/nginx
    state: present
    update-cache: yes
  tags:
    - setup

- name: Install required system packages.
  become: yes
  apt:
    pkg:
    - nginx
    - brotli
    - libnginx-mod-http-brotli
    state: present
    update-cache: yes
  tags:
    - setup

# - name: Install brotli nginx-module
#   become: yes
#   template: >
#     src=brotli-module.conf.j2
#     dest=/etc/nginx/modules-enabled/brotli-module.conf
#     force=yes
#   tags:
#     - setup

# - name: Install required system packages.
#   become: yes
#   apt: >
#     pkg=nginx
#     state=present
#     update-cache=yes
#   tags:
#     - setup

- name: Create log directory
  become: yes
  file: >
    dest={{ project_logs }}
    owner={{ project_user }}
    owner={{ project_group }}
    state=directory
  tags:
    - setup

- name: Nginx | remove default nginx site
  notify: restart nginx
  become: yes
  file: >
    path=/etc/nginx/sites-enabled/default
    state=absent
  tags:
    - setup

# Harden nginx SSL security if enabled
- name: Check for existence of dhparam.pem file
  become: yes
  when:   
    - nginx.strong_ssl|d(False) == True
  stat:
    path: "/etc/ssl/certs/dhparam.pem"
  register: dhparam_data

# This is really slow
- name: Create dhparam.pem file (This will take a while...)
  become: yes
  when:    
    - nginx.strong_ssl|d(False) == True
    - not dhparam_data.stat.exists
  shell: openssl dhparam -out /etc/ssl/certs/dhparam.pem 4096
  tags:
    - setup

- name: Install ssl-params.conf file
  become: yes
  when:    
    - nginx.strong_ssl|d(False) == True
  template: >
    src=ssl-params.conf.j2
    dest=/etc/nginx/snippets/ssl-params.conf
    force=yes
  tags:
    - setup

