---
- name: JS Application | Clone or pull git repository
  when: node_version is defined
  become: yes
  become_user: "{{ project_user }}"
  git: >
    repo={{ repo.url }}
    dest={{ project_src }}
    version={{ repo.version }}
    accept_newhostkey=yes
    force=yes
    update=yes
  tags:
    - deploy

- name: JS Application | Deps npm install application
  when: 
    - node_version is defined
    - (use_npm_install is defined) and (use_npm_install|d(False) == True)
  npm:
    path: "{{ project_src }}/{{ sub_project_src }}"
    production: false
  become: true
  become_user: "{{ project_user }}"
  tags:
    - deploy

- name: JS Application | Deps yarn install application
  when:
    - node_version is defined
    - (not use_npm_install is defined) or (use_npm_install|d(False) == False)
  yarn:
    path: "{{ project_src }}/{{ sub_project_src }}"
    production: false
  become: true
  become_user: "{{ project_user }}"
  tags:
    - deploy

- name: JS Application | Activate kendo-ui-license
  when: 
    - node_version is defined
    - kendo_ui is defined
  become: yes
  become_user: '{{ project_user }}' 
  command: 'npx kendo-ui-license activate'
  args:
    chdir:  '{{ kendo_ui.src }}'

- name: JS Application | Create .env file
  when:
    - node_version is defined
    - dot_env_file.dest is defined
    - dot_env is defined
  become: yes
  become_user: "{{ project_user }}"
  template:
    src: env-file.template
    dest: "{{ dot_env_file.dest }}"
    owner: "{{ dot_env_file.owner | default(omit) }}"
    group: "{{ dot_env_file.group | default(omit) }}"
    mode: "{{ dot_env_file.mode | default(omit) }}"
    backup: "{{ dot_env_file.backup | default(omit) }}"
    force: "{{ dot_env_file.force | default(True) }}"
    validate: "{{ dot_env_file.validate | default(omit) }}"
    selevel: "{{ dot_env_file.selevel | default(omit) }}"
    serole: "{{ dot_env_file.serole | default(omit) }}"
    setype: "{{ dot_env_file.setype | default(omit) }}"
    seuser: "{{ dot_env_file.seuser | default(omit) }}"
  tags:
    - deploy

- name: JS Application | Build application
  when: node_version is defined
  become: yes
  become_user: '{{ project_user }}' 
  command: 'yarn build'
  args:
    chdir:  '{{ project_src }}//{{ sub_project_src }}'
  environment:
    CI: "false"

- name: JS Application | Link application
  when:
    - node_version is defined
    - (not disable_app_link is defined) or (disable_app_link|d(False) == False)
  become: yes
  file:
    src: '{{ project_src }}/build'
    dest: '{{ static_root }}'
    state: link

- name: JS Application | Ensures paths dir exists
  when: copy_src_to_paths is defined
  become: yes
  become_user: '{{ project_user }}' 
  file: path={{ item }} state=directory
  with_items: "{{ copy_src_to_paths }}"
  tags:
    - deploy

- name: JS Application | Copy src directory to paths
  when: copy_src_to_paths is defined
  become: yes
  copy:
    src: "{{ project_src }}/{{ sub_project_src }}/"
    dest: "{{ item }}"
    remote_src: yes
    force: yes
    owner: "{{ project_user }}"
    group: "{{ project_group }}"
  with_items: "{{ copy_src_to_paths }}"
  tags:
    - deploy
