namespace: rizki96
name: coord
version: 0.3.8
readme: README.md
authors:
  - Iskandar Rizki <iskandar.rizki@gmail.com>
description: Ansible collection for deploying Django projects
license:
  - MIT
license_file: ''
tags: 
  - django
  - celery
  - nginx
  - uvicorn
  - postgresql
  - pyenv
  - rabbitmq
  - supervisor
  - pipenv
  - memcached
  - uwsgi
  - pip
dependencies: {}
repository: https://github.com/rizki96/ansible-coord
documentation: ''
homepage: ''
issues: https://github.com/rizki96/ansible-coord/issues
build_ignore: []

