---
- name: "Add nodejs apt key"
  when: node_version is defined
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  tags:
    - setup

- name: "Add nodejs ppa for apt repo"
  when: node_version is defined
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/{{ node_version }} {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
    allow_unauthenticated: true
  tags:
    - setup

- name: "Install nodejs"
  when: node_version is defined
  become: yes
  apt:
    update_cache: yes
    name: nodejs
    state: present
  tags:
    - setup

