---
- name: "Add nodejs apt key"
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  tags:
    - setup

- name: "Add nodejs ppa for apt repo"
  become: yes
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x {{ ubuntu_name }} main
    update_cache: yes
  tags:
    - setup

- name: "Install nodejs"
  become: yes
  apt:
    update_cache: yes
    name: nodejs
    state: present
  tags:
    - setup

