---
- name: Install dependencies of asdf
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1day
    name:
      - curl
      - git
    state: latest
  when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
  tags:
    - setup

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ ansible_user_dir }}/.asdf"
    depth: 1
    version: "{{ asdf_version | quote }}"
  register: result
  when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
  tags:
    - setup

- name: asdf update
  shell: "bash -lc 'cd {{ ansible_user_dir }}/.asdf && git pull'"
  ignore_errors: yes
  when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian') and result is failed
  tags:
    - setup

- name: set env vars
  lineinfile:
    dest: "{{ shrc_lin }}"
    state: present
    line: "{{ item.line }}"
  with_items:
    - line: ". $HOME/.asdf/completions/asdf.{{ sh_lin }}"
      regexp: '^ \. \$HOME/\.asdf/completions/asdf\.{{ sh_lin }}'
    - line: '. $HOME/.asdf/asdf.sh'
      regexp: '^ \. \$HOME/\.asdf/asdf\.sh'
  when: ansible_system == 'Linux' and (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian')
  tags:
    - setup

- name: install asdf by Homebrew
  community.general.homebrew:
    update_homebrew: true
    name:
      - asdf
  when: ansible_system == 'Darwin'
  tags:
    - setup

- name: set env vars (bash)
  lineinfile:
    dest: "{{ shprofile_mac }}"
    state: present
    line: "{{ item.line }}"
  with_items:
  - line: ".  $(brew --prefix asdf)/etc/bash_completion.d/asdf.bash"
    regexp: '^ \. \$(brew --prefix asdf)/etc/bash_completion\.d/asdf\.bash'
  - line: '. $(brew --prefix asdf)/libexec/asdf.sh'
    regexp: '^ \. \$(brew --prefix asdf)/libexec/asdf\.sh'
  when: ansible_system == 'Darwin' and sh_mac == 'bash'
  tags:
    - setup

- name: set env vars (zsh)
  lineinfile:
    dest: "{{ shrc_mac }}"
    state: present
    line: "{{ item.line }}"
  with_items:
  - line: ". $(brew --prefix)/share/zsh/site-functions"
    regexp: '^ \. \$(brew --prefix)/share/zsh/site-functions'
  - line: '. $(brew --prefix asdf)/libexec/asdf.sh'
    regexp: '^ \. \$(brew --prefix asdf)/libexec/asdf\.sh'
  when: ansible_system == 'Darwin' and sh_mac == 'zsh'
  tags:
    - setup
