---
shrc_lin: "{{ ansible_user_dir | quote }}/.{{ ansible_user_shell | basename | quote }}rc"
sh_lin: "{{ ansible_user_shell | basename | quote }}"
shprofile_mac: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename | regex_replace('$', '_') | regex_replace('zsh_', 'z') }}profile"
shrc_mac: "{{ ansible_user_dir }}/.{{ ansible_user_shell | basename }}rc"
sh_mac: "{{ ansible_user_shell | basename | quote }}"
