---
- name: ODBC | Install Apt Key from URL
  when: odbc is defined
  become: yes
  apt_key: >
    url=https://packages.microsoft.com/keys/microsoft.asc
    state=present
  # with_items: "{{ odbc }}"
  tags:
    - setup

- name: ODBC | Install Driver
  when: odbc is defined
  become: yes
  apt: >
    pkg=msodbcsql17
    state=present
    update-cache=yes
  environment: ACCEPT_EULA=Y
  tags:
    - setup
