---
#- name: ODBC | Install Apt Key from URL
#  when: odbc is defined
#  become: yes
#  apt_key: >
#    url={{ item.apt_key_url }}
#    state=present
#  with_items: "{{ odbc }}"
#  tags:
#    - deploy

- name: ODBC | Install Driver
  when: odbc is defined
  become: yes
  apt: >
    pkg=msodbcsql17
    state=present
    update-cache=yes
  tags:
    - setup
