---
- name: ODBC | Install Apt Key from URL
  when: odbc is defined
  become: yes
  apt_key: >
    url=https://packages.microsoft.com/keys/microsoft.asc
    state=present
  # with_items: "{{ odbc }}"
  tags:
    - setup

- name: ODBC | Add file apt list to the config
  when: odbc is defined
  become: yes
  apt_repository:
    repo: deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main
    state: present

- name: ODBC | Install Driver
  when: odbc is defined
  become: yes
  apt: >
    pkg=msodbcsql17
    state=present
    update-cache=yes
  environment: 
    ACCEPT_EULA: "Y"
  tags:
    - setup
