---
- name: Application Configuration
  # gather_facts: no
  hosts: 
    - '{{appservers_target|default("appservers")}}'
    - '{{taskservers_target|default("taskservers")}}'
  roles:
    - role: application
      tags:
        - application
        - django
        - flask
        - fastapi
