---
- name: Configure all cache servers
  hosts: '{{cacheservers_target|default("cacheservers")}}'
  roles:
    # - role: memcached
    #  tags:
    #    - memcached
    - role: redis
      tags:
        - redis
