---
- name: Configure all database servers
  # gather_facts: no
  hosts: '{{dbservers_target|default("dbservers")}}'
  roles:
    - role: postgres
      tags:
        - postgres
    - role: odbc
      tags:
        - odbc
