---
- name: EX Application Configuration
  # gather_facts: no
  hosts: '{{exappservers_target|default("exappservers")}}'
  roles:
    - role: exapplication
      tags:
        - exapplication
        - erlang
        - elixir
        - asdf
