---
- name: Install platform dependencies
  hosts: 
    - '{{appservers_target|default("appservers")}}'
    - '{{jsapps_target|default("jsapps")}}'
    - '{{exappservers_target|default("exappservers")}}'
  roles:
    - role: pyenv
      tags:
        - pyenv
    - role: supervisor
      tags:
        - supervisor
    - role: nodejs
      tags:
        - nodejs
    - role: yarn
      tags:
        - yarn
    - role: asdf
      tags:
        - asdf
    - role: erlang
      tags:
        - erlang
    - role: elixir
      tags:
        - elixir
