---
- name: Install platform dependencies
  hosts: 
    - '{{appservers_target|default("appservers")}}'
    - '{{jsapps_target|default("jsapps")}}'
  roles:
    - role: pyenv
      tags:
        - pyenv
    - role: supervisor
      tags:
        - supervisor
    - role: nodejs
      tags:
        - nodejs
    - role: yarn
      tags:
        - yarn