---
- name: Install platform dependencies
  hosts: '{{appservers_target|default("appservers")}}'
  roles:
    - role: pyenv
      tags:
        - pyenv
    - role: supervisor
      tags:
        - supervisor
